### PR TITLE
Error handling fixes

### LINKED ISSUE #109: Bugs: Errors Not Handled Properly
1. In New Connection Form, details for invalid connection are still added to SQLite.

https://images.zenhubusercontent.com/528556893/186e98dc-4da7-4409-addc-98b437702e85/screen_recording_2022_10_02_at_10_59_45_pm.mov

2. Clicking on a saved connection that is no longer running results in an unhandled error.

https://images.zenhubusercontent.com/528556893/46ba13d6-e899-4b3c-b924-d172fe126113/screen_recording_2022_10_02_at_11_00_13_pm.mov

### PR DESCRIPTION
**Pull request by alex-hobby**
# Description

Hotfixes:
1. When clicking on a connection for a server that is stopped, unhandled error popped up. 
2. Connections being added even if error occurred in new connection form

## Link to the issue you are closing

Fixes #109 

## Screenshot or other testing that you have completed

https://user-images.githubusercontent.com/29695042/193497088-f552c635-1f88-4a84-8b01-d5ae5e8d0db3.mov

# Checklist:

- [x] ESLint passes
- [x] Prettier passes
- [x] Included comments where necessary
- [x] Updated README if needed
- [x] Verified that code runs and generates no errors/warnings

### CODE REVIEW

**Comment by insaan21** [comment]
Looks good for the connections being incorrectly added, do you have a test for showing it fixing the unhandled error?

File: src/renderer/components/Recent.tsx [hunk 1]
```diff
@@ -20,6 +20,7 @@ const RecentList = () => {
   const handleClick = async (id: number) => {
     try {
       await window.connections.ipcRenderer.select(id);
+      await window.procedures.ipcRenderer.fetchProcedures();
```
Comment (insaan21) [inline src/renderer/components/Recent.tsx:23]: I'm not sure what this does? Fetch procedures doesn't do anything it just returns procedures and you're not assigning it to anything here?

Comment (insaan21) [reply src/renderer/components/Recent.tsx:23]: I understand why this works now, due to the fetchProcedures() invoking the error earlier and select not throwing an error, but I don't think we need to call fetchProcedures in here, we should change select to throw an error if the connection is not valid. I will add a commit that updates this

Comment (alex-hobby) [reply src/renderer/components/Recent.tsx:23]: like i mentioned, it's a hotfix, these should probably both be fixed in the backend though

**Comment by alex-hobby** [comment]
> Looks good for the connections being incorrectly added, do you have a test for showing it fixing the unhandled error?

looks like my recording got cut off at the start, will fix

**Comment by insaan21** [comment]
> > Looks good for the connections being incorrectly added, do you have a test for showing it fixing the unhandled error?
> 
> looks like my recording got cut off at the start, will fix

It's fine I got what the issue was, the change I made also works without having to call fetchProcedures()
Screen Shot 2022-10-02 at 11 34 12 PM

File: src/renderer/components/Recent.tsx (hunk 1 above)
Comment (insaan21) [reply src/renderer/components/Recent.tsx]: Oh sorry I don't know what a hotfix means

File: src/renderer/components/NewConnectionForm.tsx [hunk 2]
```diff
@@ -143,12 +143,13 @@ const NewConnectionForm = () => {
...
     try {
       // creates the server connection in sqlite and connects to it
-      await window.connections.ipcRenderer.create(connection);
+      const db = await window.connections.ipcRenderer.create(connection);
 
       // verify if server connection was established
       const verified = await window.connections.ipcRenderer.verify();
       if (!verified) {
         setAlert(true);
+        await window.connections.ipcRenderer.delete(db.id);
```
Comment (insaan21) [inline src/renderer/components/NewConnectionForm.tsx:152]: Yeah you're right this should also be done in the backend, but it is sort of hard to do with the way we've set it up right now, so we will change this when we refactor the redux state

**Review by insaan21 — APPROVED** [review]

File: src/renderer/components/Recent.tsx (hunk 1 above)
Comment (alex-hobby) [reply src/renderer/components/Recent.tsx]: maybe i'm wrong but i think it means a temporary fix to an important problem
