### PR TITLE
Check pass fail

### LINKED ISSUE #137: [B] Determine procedure pass/fail results
Given a list of conditions from front end, determine if the procedure pass/failed.
- Do any work needed before hand
  - E.x. check how many records are currently in the table
- Pass flags provided by front end through to the procedure.
- Trigger procedure
- Check conditions after

Return a list of results grouped by rule and separated by condition (rows match/do not match).

If a condition was passed, return True
If a condition was failed, return offending values

### PR DESCRIPTION
**Pull request by insaan21**
# Description

Checking pass fail conditions for an Execution 

## Link to the issue you are closing

Fixes #137 

## Screenshot or other testing that you have completed
```ts
 public async test() {
    try {
      const connection = {
        nickname: 'asdf',
        type: DBProvider.PostgreSQL,
        id: 1,
        defaultDatabase: 'React',
        address: 'localhost',
        password: 'asdf',
        username: 'kpmg',
        port: 5432,
      };
      const execution: ExecutionModelType = {
        id: 0,
        timestamp: new Date(),
        rules: [],
        connection,
      };

      const rule1: RuleModelType = {
        name: 'rule1',
        ruleId: 0,
        database: 'React',
        testData: '',
        unitTests: [],
        execution,
      };

      const rule2: RuleModelType = {
        name: 'rule2',
        ruleId: 1,
        database: 'React',
        testData: '',
        unitTests: [],
        execution,
      };
      const test1: TableTestType = {
        operation: TableGenericOperations.EXISTS,
        level: UnitTestOperations.TableGenericOperations,
        id: 0,
        name: 'test1',
        expectedRecordMatches: RecordMatches.ZERO,
        total: false,
        expectedNumRecords: 0,
        table: 'accounts',
        result: false,
        format: OutputFormat.PLAIN,
        output: '',
        rule: rule1,
      };

      const test2: TableTestType = {
        operation: TableGenericOperations.COUNT,
        level: UnitTestOperations.TableGenericOperations,
        id: 1,
        name: 'test2',
        expectedRecordMatches: RecordMatches.TABLE_ROWS,
        total: true,
        expectedNumRecords: 10,
        table: 'accounts',
        result: false,
        format: OutputFormat.PLAIN,
        output: '',
        rule: rule1,
      };

      const test3: TableTestType = {
        operation: TableGenericOperations.COUNT,
        level: UnitTestOperations.TableGenericOperations,
        id: 2,
        name: 'test3',
        expectedRecordMatches: RecordMatches.TABLE_ROWS,
        total: false,
        expectedNumRecords: 2,
        table: 'accounts',
        result: false,
        format: OutputFormat.PLAIN,
        output: '',
        rule: rule1,
      };

      const test4: RowTestType = {
        operation: RowNumberOperations.LT,
        level: UnitTestOperations.RowNumberOperations,
        id: 3,
        name: 'test4',
        expectedRecordMatches: RecordMatches.TABLE_ROWS,
        total: true,
        column: 'balance',
        expectedNumRecords: 2,
        table: 'accounts',
        result: false,
        format: OutputFormat.PLAIN,
        output: '',
        value: '200',
        rule: rule2,
      };

      const test5: RowTestType = {
        operation: RowNumberOperations.EQ,
        level: UnitTestOperations.RowNumberOperations,
        id: 4,
        name: 'test5',
        expectedRecordMatches: RecordMatches.ZERO,
        total: true,
        column: 'balance',
        expectedNumRecords: 2,
        table: 'accounts',
        result: false,
        format: OutputFormat.PLAIN,
        output: '',
        value: '100',
        rule: rule2,
      };

      rule1.unitTests = [test1, test2, test3];
      rule2.unitTests = [test4, test5];
      execution.rules = [rule1, rule2];
      this.checkPassFail('transfer2', ['1', '2', '400'], execution);
    } catch (e) {
      log.error(e);
    }
  }
```
PNG image

Screen Shot 2022-10-16 at 8 38 26 PM
Screen Shot 2022-10-16 at 8 38 30 PM

Your PR should include at least one test/screenshot in order to showcase that the changes don't break/fix what was needed. In the case of frontend, a screenshot should suffice. For backend, depending on the scenario, some temporary tests may need to be written to show that the function does what's needed.

# Checklist:

- [x] ESLint passes
- [x] Prettier passes
- [x] Included comments where necessary
- [x] Updated README if needed
- [x] Verified that code runs and generates no errors/warnings

### CODE REVIEW

**Comment by adityavidyadharan** [comment]
> Also @adityavidyadharan is the count variable supposed to represent the change in rows, or number of rows total?

For now let's just make it # of rows in the table. Once we have the skeleton of pass-fail worked out and working, we can think about how to cleanly handle conditions that need have work to be done before and after execution

File: src/db/Procedures.ts [hunk 1]
```diff
@@ -96,4 +103,37 @@ export default class Procedures {
...
+
+  public async checkPassFail(
+    procedure: string,
+    parameters: string[],
+    test: ExecutionModelType
+  ) {
+    const tableRows: { [key: string]: number } = {};
+    test.rules.forEach((rule: RuleModelType) => {
+      rule.unitTests.forEach(async (unitTest: UnitTestType) => {
+        if ('tableName' in unitTest) {
```
Comment (adityavidyadharan) [inline src/db/Procedures.ts:115]: As a cleaner way of handling this I started putting enums in my code on row-operations. I had to add the ones for table so everything compiled so once that's merged to class-transformer you can pull it and update this code

**Review by adityavidyadharan — CHANGES_REQUESTED** [review]

File: src/db/Procedures.ts (hunk 1 above)
Comment (insaan21) [reply src/db/Procedures.ts:115]: Sounds good!

Comment (adityavidyadharan) [reply src/db/Procedures.ts:115]: These are now in #153 so once that's merged you can pull and update your code

**Comment by adityavidyadharan** [comment]
I think we should separate our code out into a separate service and keep Procedures for more utility functions. I put my stuff in a RowTestService but we can make that a combined UnitTestService or something

File: src/db/service/ExecutionService.ts [hunk 2]
```diff
@@ -1,11 +1,142 @@
...
+                  }
+                  break;
+                default:
+                  unitTest.result = false;
+                  break;
+              }
+            }
+            break;
+          }
+          case UnitTestOperations.RowBooleanOperations: {
```
Comment (adityavidyadharan) [inline src/db/service/ExecutionService.ts:94]:
```suggestion
          case UnitTestOperations.RowStringOperations
          case UnitTestOperations.RowNumberOperations
          case UnitTestOperations.RowIDOperations
          case UnitTestOperations.RowBooleanOperations: {
```

Not sure if this is correct syntax wise but you should be able to do this. All of the row cases should trigger this code

**Review by adityavidyadharan — CHANGES_REQUESTED** [review]

File: src/db/service/ExecutionService.ts (hunk 2 above)
Comment (insaan21) [reply src/db/service/ExecutionService.ts:94]: Oh yeah my bad I meant to do this for all of them

File: src/db/service/ExecutionService.ts [hunk 3]
```diff
@@ -1,11 +1,142 @@
...
+                unitTest.output = JSON.stringify(rows);
+                unitTest.output = `First 10 rows: ${JSON.stringify(
+                  rows?.slice(0, 10)
+                )}`;
+                break;
+              case RecordMatches.GREATER_THAN:
+                unitTest.result = Number(rows?.length) > 0;
+                unitTest.output = `First 10 rows: ${JSON.stringify(
+                  rows?.slice(0, 10)
+                )}`;
```
Comment (adityavidyadharan) [inline src/db/service/ExecutionService.ts:113]: If you just leave this as the JSON string then in front end they can display it easily. Also there's a `format` field that can be either `string` or `json` that you should set so they know what to format it as

**Review by adityavidyadharan — CHANGES_REQUESTED** [review]

File: src/db/service/ExecutionService.ts [hunk 4]
```diff
@@ -1,11 +1,145 @@
...
   repository: Repository<ExecutionEntity>;
 
   constructor() {
     this.repository = AppDataSource.getRepository(ExecutionEntity);
   }
+
+  public async checkPassFail(
+    procedure: string,
+    parameters: string[],
+    test: ExecutionModelType
```
Comment (adityavidyadharan) [inline src/db/service/ExecutionService.ts:32]: @alex-hobby
The front end will need to pass this `ExecutionModelType` to the back end so that's the format needed for your form.

**Review by adityavidyadharan — DISMISSED** [review]
Just two minor changes

File: src/renderer/preload.d.ts [hunk 5]
```diff
@@ -47,6 +48,15 @@ declare global {
         verify(): Promise<boolean>;
       };
     };
+    executions: {
+      ipcRenderer: {
+        test(
+          procedure: string,
+          parameters: string,
+          test: ExecutionModelType
+        ): Promise<void>;
```
Comment (adityavidyadharan) [inline src/renderer/preload.d.ts:57]: not needed?

**Review by adityavidyadharan — CHANGES_REQUESTED** [review]

**Review by adityavidyadharan — APPROVED** [review]
